export const GET_PEOPLE = "GET_PEOPLE";
export const ADD_PERSON = "ADD_PERSON";
export const DELETE_PERSON = "DELETE_PERSON";
export const ADD_PERSON_SUCCESS = "ADD_PERSON_SUCCESS";
export const CLEAR_ADD_PERSON_SUCCESS = "CLEAR_ADD_PERSON_SUCCESS";
export const CREATE_ERROR = "CREATE_ERROR";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
